[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/618xl217sdq7n91q1039pwj718b8b99m-noctalia-shell-2026-03-25_e4158c7/share/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/terajaki/.cache/noctalia/placeholder.json"

