# =====================================================================
#  MangoWC / MangoWM Configuration — Main Entry Point
#  Modular design matching Hyprland & Niri structure
# =====================================================================

source = ~/.config/mango/config/autostart.conf
source = ~/.config/mango/config/general.conf
source = ~/.config/mango/config/decoration.conf
source = ~/.config/mango/config/animation.conf
source = ~/.config/mango/config/binds.conf
source = ~/.config/mango/config/rules.conf
source = ~/.config/mango/noctalia.conf
