input {
    kb_layout = us
    # follow_mouse = 2 # Click to focus
    float_switch_override_focus = 0
}

general {
    gaps_in = 10
    gaps_out = 15 # the gaps around the entire tiles
    border_size = 2
    # Not too bright borders (muted teal/green)
    col.active_border = rgba(ffffffff) 45deg #rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    resize_on_border = true
}
