# main entry point

# Source modular configuration files
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animation.conf

# keybindings
source = ~/.config/hypr/binds.conf

# plugins
source = ~/.config/hypr/plugins.conf
