-- Generated by nwg-displays on 2026-08-31 at 18:00:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1280x1024@47.55",
    position = "1392x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1280x1024@47.55",
    position = "1392x0",
    scale = 1.0
})
