$primary = rgb(e47767)
$surface = rgb(291714)
$secondary = rgb(d6a95c)
$error = rgb(b55b4e)
$tertiary = rgb(bfcc66)
$surface_lowest = rgb(150b0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
