# exec-once = waybar # quickshell
exec-once = swww-daemon
exec-once = hyprpm reload
exec-once = easyeffects
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Load the plugins from the Nix-provided path
exec-once = hyprctl plugin load $(nix-build -E 'with import <nixpkgs> {}; inputs.hyprland-plugins.packages.${system}.hyprbars' --no-out-link)/lib/libhyprbars.so
