# =====================================================================
#  config/autostart.conf — MangoWC Autostart & Environment Services
# =====================================================================

# Export systemd & D-Bus environment
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE SSH_AUTH_SOCK GNOME_KEYRING_CONTROL GNOME_KEYRING_PID
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SSH_AUTH_SOCK GNOME_KEYRING_CONTROL GNOME_KEYRING_PID
exec-once = systemctl --user start hyprpolkitagent

# Autostart Noctalia shell v5 & audio/clipboard daemons
exec-once = noctalia -d
exec-once = easyeffects --gapplication-service
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
