# =====================================================================
#  config/rules.conf — Window Rules, Tag Rules, & Opaque Overrides
# =====================================================================

# ── Tag Layout Rules ─────────────────────────────────────────────────
tagrule = id:1, layout_name:scroller
tagrule = id:2, layout_name:scroller

# ── Floating Window Rules ────────────────────────────────────────────
windowrule = isfloating:1, title:^(.scrcpy-wrapped)$
