# main entry point

# Source modular configuration files
source = ~/.config/hypr/config/startup.conf
source = ~/.config/hypr/config/general.conf
source = ~/.config/hypr/config/decoration.conf
source = ~/.config/hypr/config/animation.conf

# keybindings
source = ~/.config/hypr/config/binds.conf

# plugins
source = ~/.config/hypr/config/plugins.conf
