# exec-once = waybar # quickshell
# exec-once = swww-daemon
exec-once = noctalia-shell
exec-once = hyprpm reload
exec-once = easyeffects
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# # Specific for loading flake-provided plugins on NixOS
exec-once = hyprctl plugin load ${inputs.hyprland-plugins.packages.${pkgs.system}.hyprbars}/lib/libhyprbars.so
exec-once = hyprctl plugin load ${inputs.hyprland-plugins.packages.${pkgs.system}.hyprexpo}/lib/libhyprexpo.so
