color0 #111416
color1 #ffb4ab
color2 #90cdff
color3 #b8c8d9
color4 #d0bfe7
color5 #90cdff
color6 #b8c8d9
color7 #e2e2e5
color8 #8c9198
color9 #ffb4ab
color10 #90cdff
color11 #b8c8d9
color12 #d0bfe7
color13 #90cdff
color14 #b8c8d9
color15 #e2e2e5

cursor                #e2e2e5
cursor_text_color     #111416
background            #111416
foreground            #e2e2e5
selection_foreground  #c1c7ce
selection_background  #42474d
active_border_color   #90cdff
inactive_border_color #42474d
url_color             #90cdff

active_tab_foreground   #003350
active_tab_background   #90cdff
inactive_tab_foreground #c1c7ce
inactive_tab_background #42474d
cursor_trail_color      #c1c7ce
