{ config, lib, pkgs, inputs, ... }:
{
  environment.systemPackages = with pkgs; [
    wget
    git
    brave
    vivaldi
    fastfetch
    gamemode
    qpwgraph
    vscode-fhs
    mpv
    libreoffice-qt6-fresh
    ffmpeg
    ttyper
    ani-cli
    mov-cli
    nodejs_24
    dotool
    scrcpy
    kdePackages.applet-window-buttons6
    clang
    cmake
    pkg-config
    gnumake
    lld
    SDL2
    SDL2_image
    SDL2_mixer
    SDL2_ttf
    libpng
    libjpeg
    freetype
    libvorbis
    libogg
    gcc
    rustc
    cargo
    openssl
    python3
    python313Packages.pip
    tk
    gparted
    exfatprogs
    ntfs3g
    wine
    wineWowPackages.full
    obs-studio
    android-tools
    gptfdisk
    dmg2img
    ngrok
    samba
    gnirehtet
    guitarix
    alsa-tools
    kde-rounded-corners
    kdePackages.krdp
    libva-utils
    x264
    mapscii
    vesktop
    qbittorrent
    php
    phpExtensions.mysqli
    phpExtensions.pdo
    phpExtensions.pdo_mysql
    phpExtensions.mbstring
    phpExtensions.curl
    phpExtensions.openssl
    php83
    php83Packages.composer
  ] ++ [
    inputs.kwin-effects-forceblur.packages.${pkgs.system}.default
    inputs.kwin-effects-glass.packages.${pkgs.system}.default
  ];

  fonts.packages = with pkgs; [ nerd-fonts.jetbrains-mono ];
}
